### ISSUE TITLE
uvicorn not closing sockets

### ISSUE THREAD

**Issue by johnrtipton** [Kludex/uvicorn#1199] opened 2021-09-28 14:29 UTC
We are using the latest uvicorn 0.15.  It seems that after we upgraded to uvicorn 0.15 that our AWS load balancer health checks fail after a certain amount of time.  Upon further investigation we found that all of our sockets are being used up because they are staying open in a CLOSE_WAIT status.

```
# netstat -ant | awk '{print $6}' | sort | uniq -c | sort -n
   1 Foreign
   1 LISTEN
   1 established)
   7 TIME_WAIT
  13 ESTABLISHED
7047 CLOSE_WAIT
```

### Workaround
For now we have switched our worker from UvicornWorker to UvicornH11Worker and it has resolved our issue.

### Environment
Running uvicorn 0.15.0 with CPython 3.7.12 on Linux

**Comment by Kludex** [comment] 2021-09-28 14:35
I don't see how the change of worker class would solve this issue :thinking:

**Comment by pacoyang** [comment] 2021-09-29 06:33
> I don't see how the change of worker class would solve this issue 🤔

It maybe because h11 will close the transport when if the connection is invalid HTTP request, this issue similarity to #1192 
https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/http/h11_impl.py#L140

**Comment by johnrtipton** [comment] 2021-09-29 14:27
Yes @pacoyang this seems to be exactly the problem we are seeing.   Thanks!

**Comment by Kludex** [comment] 2021-11-05 17:42
@johnrtipton from which version did you guys upgrade? 0.13.4?

**Comment by johnrtipton** [comment] 2021-11-08 17:33
@Kludex We upgraded from `0.14.0`

**Comment by shahar-medigate** [comment] 2021-12-01 16:06
We encountered the issue in our systems as well, a simple fastapi service behind AWS EKS load-balancer
we also managed to reproduce the issue to a single commit
https://github.com/encode/uvicorn/commit/960d4650db0259b64bc41f69bc7cdcdb1fdbcbf3

A simple program to reproduce
```python
import uvicorn

async def app(scope, receive, send):
    assert scope["type"] == "http"

    await send(
        {
            "type": "http.response.start",
            "status": 200,
            "headers": [
                [b"content-type", b"text/plain"],
            ],
        }
    )
    await send(
        {
            "type": "http.response.body",
            "body": b"Hello, world!",
        }
    )


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", reload=False, log_level=5)
```

and run `nc -z localhost:8000`
now you will have a new CLOSE_WAIT connection with netstat

apparently, it got something to do with uvloop don't call connection_lost or something
we bypass the issue by setting `loop="asyncio"` to the run function

**Comment by Anton-2** [comment] 2022-01-20 12:56
Same thing here using [Koyeb](https://www.koyeb.com): the health check is also a TCP connection with no data, and ends with a socket in CLOSE_WAIT state. After some time, the service stops responding due to resource exhaustion.
In the same conditions, uvicorn with #1332 works flawlessly.

**Comment by jalaziz** [comment] 2022-01-30 08:08
Looks like #1332 was released with 0.17.1 and this can be closed?

**Closed as completed** 2022-01-30 09:26 UTC
Labels: bug, help wanted, http/httptools

**Comment by pkit** [comment] 2023-08-13 17:41
Dunno, why it is closed, still happens all the time.

**Comment by pkit** [comment] 2023-08-13 17:44
Lol, reverted in 2022.

**Comment by Kludex** [comment] 2023-08-13 17:53
This issue was solved. If you have a similar issue, please create a discussion.
