### ISSUE TITLE
16,000 simultaneous request with 16 workers

### ISSUE THREAD

**Issue by lloydllim** [Kludex/uvicorn#2162] opened 2023-11-28 02:03 UTC
### Initial Checks

- [X] I confirm this was discussed, and the maintainers suggest I open an issue.
- [X] I'm aware that if I created this issue without a discussion, it may be closed without a response.

### Discussion Link

```Text
https://github.com/encode/uvicorn/discussions/2157
```

### Description

It returns out error 404 resource not found when I try to send out thousands of requests simultaneously to the server I have tested it both in client side code and through cmd's httpie, this confirms the error is on the server side. I have tried 100 requests and it works so I confirm that this only happens when sending a thousand request, I was expecting that the requests will be divided into 1 core = 1,000 requests, since I set 16 in my workers and im running on ryzen7 with 16 cores.
In my example code it is using black sheep but I have also tried it with fastAPI and still the same error

### Example Code

```Python
multithread_server.py


# stdlib imports:
import asyncio
import os

# 3rd-party imports:
from blacksheep import Application # pip install blacksheep
import uvicorn # pip install uvicorn

app = Application()

class TestGG:
	def __init__( self ):
		pass
	
	def set_value( self, value ):
		self.value = value
	
	def get_value( self ) :
		return self.value

TESTGG = TestGG()

def sieve_of_eratosthenes( limit: int ) -> list[int]:
	primes: list[int] = []
	sieve = [ True ] * ( limit + 1 )
	for num in range(2, int(limit**0.5) + 1):
		if sieve[num]:
			primes.append(num)
	for multiple in range(num * num, limit + 1, num):
		sieve[multiple] = False
	for num in range(int(limit**0.5) + 1, limit + 1):
		if sieve[num]:
			primes.append(num)
	return primes


@app.on_start
async def before_start( application: Application ) -> None:
	TESTGG.set_value( 'iam a value initialized before start' )
	TESTGG.another_value = "im an another value initialized from on_start"
	TESTGG.sieve = sieve_of_eratosthenes
	application.router.gg = TESTGG

@app.router.get( "/primes/{number}" )
def index_primes( number ):
	
	TESTGG.sieve( int( number ))
	worker_id = os.getpid()
	
	return f"Worker: {worker_id}"

def main ( ) :
	uvicorn.run(
		'multithread_server:app',
		host = '127.0.0.1',
		port = 5000,
		log_level = 'info',
		workers = 16,
	)

if __name__ == '__main__':
	asyncio.run( main() )
```

multithread_client.py
```

import aiohttp
import asyncio
import time

async def get_primes( limit: int ) -> tuple[str,float]:
	async with aiohttp.ClientSession() as session:
		url = f'http://127.0.0.1:5000/primes/{limit}'
		
		# Record the start time
		start = time.time()
		
		async with session.get(url) as response:
			result = await response.text()
		
		# Calculate the time duration
		end = time.time()
		
		return result, start, end

async def main():
	# Specify the limit values you want to test

	limit_values = [ 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800 ] * 1000
	limit_values = [ x * 1000 for x in limit_values ]
	
	# limit_values = [50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000, 550000, 600000, 650000, 700000, 750000, 800000]

	tasks = [ get_primes(limit) for limit in limit_values ]

	print ( len (tasks) )
	# asyncio.gather is more like of a Promise.all in JS that will take a list of functions and run it concurrently
	try:
		results_with_duration = await asyncio.gather( *tasks )
		print( f'{results_with_duration=}')

		for i, (limit, (result, start, end)) in enumerate(zip(limit_values, results_with_duration), 1):
			print( f'{i=} {start=} {end=} {limit=} {result=}' )

	except Exception as e:
		print( f' {e=}')
	

if __name__ == '__main__':
	asyncio.run(main())
```

multithread_client_cmd.bat
```

@echo off


for /l %%i in (1, 1, 16000) do (
    echo This is iteration %%i
    rem Add your commands here
    set n = %%i * 1000
    start cmd /k "http GET http://127.0.0.1:5000/primes/%n%"
)

start cmd /k "http GET http://127.0.0.1:5000/primes/5001"
start cmd /k "http GET http://127.0.0.1:5000/primes/5003"
start cmd /k "http GET http://127.0.0.1:5000/primes/5007"
start cmd /k "http GET http://127.0.0.1:5000/primes/5009"
start cmd /k "http GET http://127.0.0.1:5000/primes/5011"
start cmd /k "http GET http://127.0.0.1:5000/primes/5013"
start cmd /k "http GET http://127.0.0.1:5000/primes/5015"
start cmd /k "http GET http://127.0.0.1:5000/primes/5017"
start cmd /k "http GET http://127.0.0.1:5000/primes/5019"
start cmd /k "http GET http://127.0.0.1:5000/primes/5021"
start cmd /k "http GET http://127.0.0.1:5000/primes/5023"
start cmd /k "http GET http://127.0.0.1:5000/primes/5025"
start cmd /k "http GET http://127.0.0.1:5000/primes/5029"
start cmd /k "http GET http://127.0.0.1:5000/primes/5031"
start cmd /k "http GET http://127.0.0.1:5000/primes/5025"
start cmd /k "http GET http://127.0.0.1:5000/primes/5095"
```
```


### Python, Uvicorn & OS Version

```Text
Running uvicorn 0.24.0.post1 with CPython 3.11.5 on Windows
```

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/2162">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/2162/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/2162/pledge.svg">
</picture>
</a>

**Comment by remdragon** [comment] 2023-11-29 18:50
This is also happening on my 16 core Ryzen 7 4800H

**Comment by Kludex** [comment] 2024-02-10 09:13
I can't reproduce it. Any way to reproduce this on a pipeline on GitHub actions or something?

**Comment by Kludex** [comment] 2024-02-10 14:36
> I can't reproduce it. Any way to reproduce this on a pipeline on GitHub actions or something?

I'll close this preemptively, please provide the above if you want us to continue.

**Closed as not planned by Kludex** 2024-02-10 14:36 UTC
Labels: need confirmation
