### ISSUE TITLE
websockets.exceptions.ConnectionClosedError - while performing simple load test on webscokets 

### ISSUE THREAD

**Issue by 29swastik** [Kludex/uvicorn#1910] opened 2023-03-22 17:35 UTC
I'm performing simple load test on FastApi websockets using [artillery](https://www.artillery.io/) and I'm seeing below error sometimes (can't really say this error is because of increase in load, sometimes I see this error for very first connection also)

**error**
```py
websockets.exceptions.ConnectionClosedError: received 1005 (no status code [internal]); then sent 1005 (no status code [internal])
```

**Code**

```py
from typing import List

import uvicorn
from fastapi import FastAPI, WebSocket

app = FastAPI()


class ConnectionManager:
    def __init__(self):
        self.active_connections: List[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)

    def disconnect(self, websocket: WebSocket):
        self.active_connections.remove(websocket)

    async def send_personal_message(self, message: str, websocket: WebSocket):
        await websocket.send_text(message)

    async def broadcast(self, message: str):
        for connection in self.active_connections:
            await connection.send_text(message)


@app.websocket('/ws')
async def stt(ws: WebSocket):
    await manager.connect(ws)
    print("Connection accepted")
    message = await ws.receive_text()
    print(f"received message: {message}")
    await ws.send_text(f"You said: {message}")


if __name__ == '__main__':
    manager = ConnectionManager()
    uvicorn.run(app=app, port=8082)
```

So here getting the above error while sending back received text back to client, at below line
```py
    await ws.send_text(f"You said: {message}")
```

**Complete Stack trace**
```py
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 51, in __call__
    await self.app(scope, receive, send)
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/starlette/routing.py", line 334, in handle
    await self.app(scope, receive, send)
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/starlette/routing.py", line 81, in app
    await func(session)
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/fastapi/routing.py", line 287, in app
    await dependant.call(**values)
  File "/Users/swastikn/my-projects/speech_to_text/sst/ws.py", line 35, in stt
    await ws.send_text(f"You said: {message}")
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/starlette/websockets.py", line 163, in send_text
    await self.send({"type": "websocket.send", "text": data})
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/starlette/websockets.py", line 85, in send
    await self._send(message)
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 327, in asgi_send
    await self.send(data)  # type: ignore[arg-type]
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/swastikn/my-projects/speech_to_text/venv/lib/python3.7/site-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1005 (no status code [internal]); then sent 1005 (no status code [internal])
INFO:     connection closed
```

**artillery config.yml**
```yml
config:
  target: "ws://127.0.0.1:8082/ws"
  ws:
    maxRedirects: 25
  phases:
    - duration: 3
      arrivalRate: 1
      rampTo: 3
      name: "Max load"
scenarios:
  - engine: "ws"
    flow:
      - send: "hello world"
 ```

**Note**

1. `uvicorn==0.19.0` (can reproduce issue with newer version **0.21.1** also)
2. `fastapi==0.86.0`
3. `websockets==10.4`

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/1910">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/1910/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/1910/pledge.svg">
</picture>
</a>

**Comment by parthvnp** [comment] 2023-04-26 20:34
Happy to work on this issue!

**Comment by Kludex** [comment] 2023-04-27 15:24
@parthvnp I don't remember if this is really an issue, but feel free to investigate, and create a PR if it is.

**Comment by parthvnp** [comment] 2023-05-07 05:21
@29swastik  This does not appear to be a bug in uvicorn. Upon extensive review, I believe the issue is caused by artillery. After analyzing logs produced by uvicorn at the debug level,  I noticed the following sequence of events occurring. 
1. The connection is accepted.
2. Artillery sends a message specified in the config file, i.e . `hello world`.
3. Artillery sends a close request with status code `1005`. As a result when you attempt to send a message it fails as the connection is closed. 

To illustrate this, try load testing with the following modifications:

```python
@app.websocket('/ws')
async def stt(ws: WebSocket):
    print(ws.client)
    await manager.connect(ws)
    print("Connection accepted")
    message = await ws.receive_text()
    second_message_sent_but_not_handled = await ws.receive()
    print(f"Received message: {second_message_sent_but_not_handled}")
    # await ws.send_text(f"You said: {message}")
    
if __name__ == '__main__':
    manager = ConnectionManager()
    uvicorn.run(app=app, port=8082, log_level="debug")

``` 
If you try running this with log_level set to `debug` for uvicorn, you will notice the following logs being produced
```python
Connection accepted
DEBUG:    > HTTP/1.1 101 Switching Protocols
DEBUG:    > Upgrade: websocket
DEBUG:    > Connection: Upgrade
DEBUG:    > Sec-WebSocket-Accept: lyvPeKLsAviTVN/stgYg+FvpbrU=
DEBUG:    > Sec-WebSocket-Extensions: permessage-deflate
DEBUG:    > date: Sun, 07 May 2023 05:02:05 GMT
DEBUG:    > server: uvicorn
INFO:     connection open
DEBUG:    = connection is OPEN
DEBUG:    < TEXT 'hello world' [11 bytes]
DEBUG:    < CLOSE 1005 (no status code [internal]) [0 bytes]
DEBUG:    = connection is CLOSING
DEBUG:    > CLOSE 1005 (no status code [internal]) [0 bytes]
DEBUG:    x half-closing TCP connection
DEBUG:    = connection is CLOSED
Received message: {'type': 'websocket.disconnect', 'code': 1005}
INFO:     connection closed
```
As you can see, because we failed to handle the connection close request sent by artillery, if you attempt to send a message using `send_text`, the `WebSocketCommonProtocol.ensure_open` will raise `ConnectionClosedError` exception hence the provided stack trace.  As to why Artillery sends `1005` I am not sure. 

Furthermore, it should also be noted the `ws` engine underlying artillery supports the ability to capture and analyze the message received from the server. See [Issue 917](https://github.com/artilleryio/artillery/pull/917) on artillery to see how to implement such functionality.

**Comment by parthvnp** [comment] 2023-05-07 05:21
@Kludex  I think we can close this issue now.

**Comment by omer-glazer** [comment] 2023-05-17 08:56
@parthvnp First of all, thanks for the help. I'm also encountering the same issue when using Channels. So is there a way around this issue without implementing my own functionality?

**Comment by parthvnp** [comment] 2023-05-18 00:34
@omer-glazer If this error occurs during load testing then you must consult the documentation for the corresponding documentation to handle this. For artillery, for instance, you can provide a `think` step in the config to ensure that you can send a message before the connection is closed. If this issue occurs in non-load testing scenario, you must ensure that the connection is not closed before you attempt to send the message. If this doesn't help, I will will more than happy to address your concern if you provide more detail in the form of stack trace as well as config you are using for performing load testing.

**Comment by omer-glazer** [comment] 2023-05-18 10:08
@parthvnp Thanks for the detailed response. Well actually, this issue occurs to me in random places. Sometimes even as a response to an HTTP API call. The exception in all cases comes from this stack trace:

ConnectionResetError: Connection lost
  File "redis/asyncio/connection.py", line 792, in send_packed_command
    await self._writer.drain()
  File "asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionError: Error UNKNOWN while writing to socket. Connection lost.
  File "uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "channels/security/websocket.py", line 37, in __call__
    return await self.application(scope, receive, send)
  File "channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "channels/routing.py", line 150, in __call__
    return await application(
  File "channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "channels/utils.py", line 58, in await_many_dispatch
    await task
  File "channels/utils.py", line 50, in await_many_dispatch
    result = task.result()
  File "channels_redis/core.py", line 347, in receive
    message_channel, message = await self.receive_single(
  File "channels_redis/core.py", line 402, in receive_single
    content = await self._brpop_with_clean(
  File "channels_redis/core.py", line 238, in _brpop_with_clean
    await connection.eval(cleanup_script, 0, channel, backup_queue)
  File "redis/asyncio/client.py", line 531, in execute_command
    return await asyncio.shield(
  File "redis/asyncio/client.py", line 505, in _try_send_command_parse_response
    return await conn.retry.call_with_retry(
  File "redis/asyncio/retry.py", line 62, in call_with_retry
    await fail(error)
  File "redis/asyncio/client.py", line 501, in _disconnect_raise
    raise error
  File "redis/asyncio/retry.py", line 59, in call_with_retry
    return await do()
  File "redis/asyncio/client.py", line 487, in _send_command_parse_response
    await conn.send_command(*args)
  File "redis/asyncio/connection.py", line 812, in send_command
    await self.send_packed_command(
  File "redis/asyncio/connection.py", line 803, in send_packed_command
    raise ConnectionError( 
  .....
  ConnectionClosedError: sent 1000 (OK); no close frame received
  File "websockets/legacy/server.py", line 248, in handler
    await self.close()
  File "websockets/legacy/protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "websockets/legacy/protocol.py", line 1232, in write_close_frame
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "websockets/legacy/protocol.py", line 1205, in write_frame
    await self.drain()
  File "websockets/legacy/protocol.py", line 1194, in drain
    await self.ensure_open()
  File "websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()

**Comment by parthvnp** [comment] 2023-05-18 13:45
@omer-glazer Thanks, I will have a look at it. Could you also, if possible, provide a minimal reproducible example for this as the exception appears to be invoked when performing some operation through `redis` client?

**Comment by omer-glazer** [comment] 2023-05-18 13:58
@parthvnp Here's the thing, this only happens in production env hosted in the cloud. No errors whatsoever locally. My guess is that there's a closed connection for an unknown reason (and for that reason it happens randomly), whilst the middleware tries to pass the scope.

**Comment by likecodingloveproblems** [comment] 2023-09-21 21:40
I think this issue may be closed! @Kludex

**Comment by Kludex** [comment] 2023-09-22 04:50
Thanks

**Closed as completed by Kludex** 2023-09-22 04:50 UTC
Labels: websockets, good first issue
