### ISSUE TITLE
autoreload got PermissionError after any exception on windows

### ISSUE THREAD

**Issue by trim21** [Kludex/uvicorn#684] opened 2020-05-27 19:25 UTC
```
INFO:     Application startup complete.
INFO:     <Server sockets=[<socket.socket fd=592, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 8000)>]> is serving
WARNING:  Detected file change in 'app\fast.py'. Reloading...
2020-05-28 03:23:58.519 | DEBUG    | app.log:setup_logger:24 - setup logger
2020-05-28 03:23:58.748 | DEBUG    | app.middlewares.sentry:setup_sentry:14 - setup sentry
WARNING:  Executing <Task finished coro=<Server.serve() done, defined at C:\Users\Trim21\.venv\pol\lib\site-packages\uvicorn\main.py:384> exception=NameError("name 'a' is not defined") created at C:\Users\Trim21\scoop\apps\python37\3.7.7\lib\asyncio\base_events.py:566> took 0.782 seconds
Process SpawnProcess-2:
Traceback (most recent call last):
  File "C:\Users\Trim21\scoop\apps\python37\3.7.7\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Trim21\scoop\apps\python37\3.7.7\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\uvicorn\subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\uvicorn\main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Users\Trim21\scoop\apps\python37\3.7.7\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\uvicorn\main.py", line 389, in serve
    config.load()
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\uvicorn\config.py", line 288, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\Trim21\scoop\apps\python37\3.7.7\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\app\fast.py", line 111, in <module>
    a
NameError: name 'a' is not defined
WARNING:  Detected file change in 'app\fast.py'. Reloading...
Traceback (most recent call last):
  File "C:\Users\Trim21\scoop\apps\python37\3.7.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Trim21\scoop\apps\python37\3.7.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\uvicorn\__main__.py", line 4, in <module>
    uvicorn.main()
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\uvicorn\main.py", line 331, in main
    run(**kwargs)
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\uvicorn\main.py", line 348, in run
    supervisor.run()
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\uvicorn\supervisors\basereload.py", line 44, in run
    self.restart()
  File "C:\Users\Trim21\.venv\pol\lib\site-packages\uvicorn\supervisors\basereload.py", line 65, in restart
    os.kill(self.process.pid, signal.SIGTERM)
PermissionError: [WinError 5] 拒绝访问。

Process finished with exit code 1
```

uvicorn = "0.11.5"

```console
python.exe -W ignore -m uvicorn app.fast:app --loop asyncio --use-colors --reload --reload-dir app --lifespan on --host localhost
```

**Comment by euri10** [comment] 2020-05-28 07:30
can you check if you got the same on python 3.8, I kind of remember there was a multiprocessing python bug, cant find it now

**Comment by trim21** [comment] 2020-05-28 13:34
same problem on python3.8

**Comment by trim21** [comment] 2020-05-28 13:36
fixed by ignore OSError...

```python
        try:
            os.kill(self.process.pid, signal.SIGTERM)
        except OSError:
            pass
```

I guess it's not a bug of `multiprocessing`, but the the process is not running.

(sorry for my poor English)

**Comment by abersheeran** [comment] 2020-08-01 08:05
I get the same error in here.

**Comment by euri10** [comment] 2020-08-01 13:38
I'm sorry I cant reproduce, just install a win10 machine and used the same command line as provided, it reloads fine, and several times in a row.

that said we made several changes on the relaoder from the time you reported the issue and added some windows CI tests that dont exhibit an issue with reloader, 

so I'm going to close this now as non-reproducible, but feel free to open another ticket if that not still solved on latest version using the new issue template that asks quite a lot of info but would help narrowing where there might be an issue.

thanks

**Comment by euri10** [comment] 2020-08-01 13:41
ok I just reproduced, it's when it's raising an exception, totally misread hte case sorry :)

**Comment by abersheeran** [comment] 2020-08-01 16:46
I checked the code, the problem here is that the child process exits abnormally after restarting. The main process did not detect this problem, so the dead process could not be killed in a new round of restart, resulting in an exception being thrown. @euri10

**Comment by abersheeran** [comment] 2020-08-04 12:27
@euri10 Let me explain in more detail how to reproduce the problem.

1. Create a project and start it with uvicorn.
2. Modify the code in the project to make the code throw a SyntaxError. 
3. Then modify the code correctly. You will see uvicorn fail to restart.

This is not a problem with the Windows platform, you should be able to reproduce it on all platforms.

**Comment by euri10** [comment] 2020-08-04 12:43
I was able to reproduce on windows but it seems to me it's the only plateform, see on debian:

```
/home/lotso/PycharmProjects/uvicorn/venv/bin/python -m uvicorn app:app --reload
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [15496] using watchgod
INFO:     Started server process [15518]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
WARNING:  Detected file change in '['/home/lotso/PycharmProjects/uvicorn/app.py']'. Reloading...
INFO:     Shutting down
INFO:     Finished server process [15518]
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/home/lotso/.asdf/installs/python/3.8.5/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/lotso/.asdf/installs/python/3.8.5/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "./uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "./uvicorn/main.py", line 397, in serve
    config.load()
  File "./uvicorn/config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "./uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/lotso/.asdf/installs/python/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app.py", line 16
    ewrfweqt;fglkmnevp f
                       ^
IndentationError: unindent does not match any outer indentation level
WARNING:  Detected file change in '['/home/lotso/PycharmProjects/uvicorn/app.py']'. Reloading...
INFO:     Started server process [16121]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     127.0.0.1:49552 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:49552 - "GET /favicon.ico HTTP/1.1" 200 OK
WARNING:  Detected file change in '['/home/lotso/PycharmProjects/uvicorn/app.py']'. Reloading...
INFO:     Shutting down
INFO:     Finished server process [16121]
INFO:     Started server process [17160]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     127.0.0.1:49706 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:49706 - "GET /favicon.ico HTTP/1.1" 200 OK
WARNING:  Detected file change in '['/home/lotso/PycharmProjects/uvicorn/app.py']'. Reloading...
INFO:     Shutting down
INFO:     Finished server process [17160]
Process SpawnProcess-5:
Traceback (most recent call last):
  File "/home/lotso/.asdf/installs/python/3.8.5/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/lotso/.asdf/installs/python/3.8.5/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "./uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "./uvicorn/main.py", line 397, in serve
    config.load()
  File "./uvicorn/config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "./uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/lotso/.asdf/installs/python/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app.py", line 15, in <module>
    d
NameError: name 'd' is not defined
WARNING:  Detected file change in '['/home/lotso/PycharmProjects/uvicorn/app.py']'. Reloading...
Process SpawnProcess-6:
Traceback (most recent call last):
  File "/home/lotso/.asdf/installs/python/3.8.5/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/lotso/.asdf/installs/python/3.8.5/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "./uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "./uvicorn/main.py", line 397, in serve
    config.load()
  File "./uvicorn/config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "./uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/lotso/.asdf/installs/python/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app.py", line 1
    async def app(scope, receive, send)
                                      ^
SyntaxError: invalid syntax
WARNING:  Detected file change in '['/home/lotso/PycharmProjects/uvicorn/app.py']'. Reloading...
INFO:     Started server process [18227]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
```

**Comment by abersheeran** [comment] 2020-08-04 12:46
Maybe the behavior of `os.kill` is different on some platforms.

**Closed as completed** 2020-08-27 08:53 UTC
