### ISSUE TITLE
uvicorn adds empty Sec-Websocket-Protocol during websockets handshake

### ISSUE THREAD

**Issue by godovdm** [Kludex/uvicorn#534] opened 2019-12-20 09:58 UTC
Hello! I found that uvicorn adds empty Sec-Websocket-Protocol header during websockets connection if a client does not send the header on handshake start. It pervents Chrome to connect to websocket endpoint with error:

> Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request:

```
GET / HTTP/1.0
Host: localhost
Upgrade: websocket
Connection: upgrade
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: tqGbvpu0YwSLRJzdkVz7pA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits```

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: 8JVIJxqOLVHldmdE54jsX5SxKKY=
Sec-WebSocket-Protocol: 
Server: Python/3.7 websockets/8.1
```
Firefox works just fine. Seems it just ignores empty header, but Chrome is stricter.

uvicorn version 0.9.0

**Comment by euri10** [comment] 2019-12-20 10:45
are you sure it's uvicorn adding it ?
looking at the code the only time the header is used is in 
https://github.com/encode/uvicorn/blob/8a67c3c08d4a46b46865ea249f9714ce346beca0/uvicorn/protocols/websockets/websockets_impl.py#L93-L94

**Comment by godovdm** [comment] 2019-12-20 11:07
We have nginx before uvicorn and uvicorn is serving sanic app. I tried to run sanic development server and proxy requests directly to it and it was ok, chrome successfully connected to ws endpoint. So I decided it is uvicorn problem :) We configured nginx to hide this header and it works fine, but it looks like a hack... May be I can perform some additional tests, but I don't know where to see.

**Comment by euri10** [comment] 2020-12-29 21:00
I just played a little bit with Chrome and subprotcols and didnt find a way to have uvicorn send back the subprotocol header Sec-Websocket-Protocol without setting it in the handshae request beforehand.
I'm gonna close it as cant reproduce, but feel free to add an example that fails so we can investigate, thanks

**Closed as completed by euri10** 2020-12-29 21:00 UTC
Labels: websockets, need confirmation
