### ISSUE TITLE
Feature Request: Allow for multiple file types to trigger reload

### ISSUE THREAD

**Issue by seanaye** [Kludex/uvicorn#605] opened 2020-03-31 19:00 UTC
Im using uvicorn as a server in a graphql application and it would be nice if you could pass uvicorn multiple file types to watch instead of only .py files

In my case this would be .py and .graphql files.

**Comment by florimondmanca** [comment] 2020-04-02 09:30
Most likely a duplicate of #528. There’s also an existing PR: #550.

**Comment by euri10** [comment] 2020-04-02 10:16
indeed and his implementation is faster than me using glob :)

**Comment by rafalp** [comment] 2020-04-10 10:58
Closing as dupe of #528, but don't worry - I _feel the pain_ and I'll look into it hopefully soon!

**Closed as completed by rafalp** 2020-04-10 10:58 UTC
