### ISSUE TITLE
protocols.utils.get_local_addr ValueError with socket

### ISSUE THREAD

**Issue by bukowa** [Kludex/uvicorn#733] opened 2020-07-30 14:24 UTC
**version**: 0.11.7

this line causes trouble https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/utils.py#L39

value of `info` variable: `/socket/socket.sock`

command:
````
uvicorn --uds /socket/socket.sock --interface=asgi3 --lifespan=off --log-level=trace --use-colors --proxy-headers dim_django.asgi:application
````

trace line is different due to added logging
````python
django_1  | INFO:     Started server process [10]
django_1  | INFO:uvicorn.error:Started server process [10]
django_1  | INFO:     Uvicorn running on unix socket /socket/socket.sock (Press CTRL+C to quit)
django_1  | INFO:uvicorn.error:Uvicorn running on unix socket /socket/socket.sock (Press CTRL+C to quit)
django_1  | INFO:root:/socket/socket.sock
django_1  | ERROR:asyncio:Exception in callback UVTransport._call_connection_made
django_1  | handle: <Handle UVTransport._call_connection_made>
django_1  | Traceback (most recent call last):
django_1  |   File "uvloop/cbhandles.pyx", line 73, in uvloop.loop.Handle._run
django_1  |   File "uvloop/handles/basetransport.pyx", line 134, in uvloop.loop.UVBaseTransport._call_connection_made
django_1  |   File "uvloop/handles/basetransport.pyx", line 131, in uvloop.loop.UVBaseTransport._call_connection_made
django_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 132, in connection_made
django_1  |     self.server = get_local_addr(transport)
django_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/utils.py", line 45, in get_local_addr
django_1  |     return (str(info[0]), int(info[1]))
django_1  | ValueError: invalid literal for int() with base 10: 's'

````
https://github.com/encode/uvicorn/issues/600

nginx config:
````
upstream django {
  server unix:/socket/socket.sock;
}
server {

  listen 9000;
  server_name localhost;

  location /static/ {
    autoindex off;
    alias /static/;
  }

  location / {
    proxy_pass http://django/;
  }
````

**Comment by euri10** [comment] 2020-07-31 09:58
thanks, going to close as a duplicate of #727 
hopefully fixed soon

**Closed as completed by euri10** 2020-07-31 09:58 UTC
