### ISSUE TITLE
asyncio.exceptions.CancelledError with asyncio  

### ISSUE THREAD

**Issue by wanghaisheng** [Kludex/uvicorn#2173] opened 2023-12-01 01:35 UTC
### Initial Checks

- [X] I confirm this was discussed, and the maintainers suggest I open an issue.
- [X] I'm aware that if I created this issue without a discussion, it may be closed without a response.

### Discussion Link

```Text
yes
```

### Description

I am building a tkinter gui and in the background host a fastapi and uvicorn server for static files. here i want to exit program when hit system tray menu ,it do but a lot of error related to how i start a uvicorn server with asyncio

```
INFO:     Started server process [4692]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
shutdown icon
shutdown server
INFO:     Shutting down
INFO:     Shutting down
shutdown root
shutdown loop
An error occurred when calling message handler
Traceback (most recent call last):
  File "D:\program\miniconda\lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
  File "D:\program\miniconda\lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
  File "D:\program\miniconda\lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
  File "D:\program\miniconda\lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
  File "D:\workspace\tiktoka\tiktoka-studio-uploader-genius\t.py", line 65, in quit_window
    loop.close()
  File "D:\program\miniconda\lib\asyncio\proactor_events.py", line 681, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
Traceback (most recent call last):
  File "D:\workspace\tiktoka\tiktoka-studio-uploader-genius\t.py", line 128, in <module>
    loop.run_forever()
  File "D:\program\miniconda\lib\asyncio\windows_events.py", line 319, in run_forever
ERROR:    Traceback (most recent call last):
  File "D:\program\miniconda\lib\site-packages\starlette\routing.py", line 686, in lifespan
    await receive()
  File "D:\program\miniconda\lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
  File "D:\program\miniconda\lib\asyncio\queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

    assert self._self_reading_future is None
AssertionError
Exception in thread Thread-1 (start_fastapi_server):
Traceback (most recent call last):
  File "D:\program\miniconda\lib\site-packages\uvicorn\server.py", line 82, in serve
    await self.shutdown(sockets=sockets)
  File "D:\program\miniconda\lib\site-packages\uvicorn\server.py", line 275, in shutdown
    await asyncio.sleep(0.1)
  File "D:\program\miniconda\lib\asyncio\tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\program\miniconda\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\program\miniconda\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\workspace\tiktoka\tiktoka-studio-uploader-genius\t.py", line 88, in start_fastapi_server
    loop.run_until_complete(server.serve())
  File "D:\program\miniconda\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
```

### Example Code

```Python
import sys
import threading
from fastapi import FastAPI
from fastapi.responses import FileResponse

from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pystray import MenuItem as item
import pystray
from PIL import Image, ImageTk
import asyncio
import tkinter as tk


app = FastAPI()
# Allow all origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # You can replace this with specific origins if needed
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def start(lang, root=None, async_loop=None):
    global mainwindow, canvas

    # root.resizable(width=True, height=True)
    root.iconbitmap("assets/icon.ico")
    root.title('tkinter asyncio demo')


    root.update_idletasks()



def quit_window(icon, item):
    global loop,fastapi_thread

    print('shutdown icon')

    icon.stop()



    print('shutdown server')
    server.should_exit = True
    server.force_exit = True
    asyncio.run(server.shutdown())


    try:
        tasks = asyncio.all_tasks(loop)
        for task in tasks:
            task.cancel()
    except RuntimeError as err:
        print('SIGINT or SIGTSTP raised')
        print("cleaning and exiting")
        sys.exit(1)    
    print('shutdown root')

    root.destroy()
    print('shutdown loop')

    loop.close()
    # loop.stop()
    # loop.run_until_complete(asyncio.gather(*[shutdown()]))
    # os._exit(0)

def show_window(icon, item):
    icon.stop()
    root.after(0, root.deiconify)


def withdraw_window():
    root.withdraw()
    image = Image.open("assets/icon.ico")
    menu = (item("Quit", quit_window), item("Show", show_window))
    icon = pystray.Icon("name", image, "title", menu)
    # icon.run_detached()
    icon.run()

def start_fastapi_server(loop):
    import uvicorn
    global server
    config = uvicorn.Config(app, loop=loop, host="0.0.0.0", port=8000)
    server = uvicorn.Server(config)
    loop.run_until_complete(server.serve())





def start_tkinter_app(async_loop):
    global root, settings, db, canvas, locale
    root = tk.Tk()

    locale = 'en'
    start(locale, root, async_loop)

    root.protocol('WM_DELETE_WINDOW', withdraw_window)


    root.mainloop()




if __name__ == "__main__":
    global loop,fastapi_thread
    loop=None
    if sys.platform == 'win32':
        asyncio.get_event_loop().close()
        # On Windows, the default event loop is SelectorEventLoop, which does
        # not support subprocesses. ProactorEventLoop should be used instead.
        # Source: https://docs.python.org/3/library/asyncio-subprocess.html
        loop = asyncio.ProactorEventLoop()
        asyncio.set_event_loop(loop)
    else:
        loop = asyncio.get_event_loop()

    # Start FastAPI server in a separate thread
    fastapi_thread = threading.Thread(target=start_fastapi_server,args=(
            loop,)).start()


    start_tkinter_app(loop)
    loop.run_forever()
    loop.close()
```
```


### Python, Uvicorn & OS Version

```Text
Running uvicorn 0.24.0.post1 with CPython 3.10.10 on Windows
```

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/2173">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/2173/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/2173/pledge.svg">
</picture>
</a>

**Comment by wanghaisheng** [comment] 2023-12-01 03:06
```
import sys
import threading
from fastapi import FastAPI
from fastapi.responses import FileResponse

from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pystray import MenuItem as item
import pystray
from PIL import Image, ImageTk
import asyncio
import tkinter as tk
from asyncio import CancelledError
from contextlib import suppress

app = FastAPI()
# Allow all origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # You can replace this with specific origins if needed
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def start(lang, root=None, async_loop=None):
    global mainwindow, canvas

    # root.resizable(width=True, height=True)
    root.iconbitmap("assets/icon.ico")
    root.title('tkinter asyncio demo')


    root.update_idletasks()

async def wait():


    try:
        tasks = asyncio.all_tasks(loop)
        print(f'========{tasks}')
        for task in tasks:
            try:
                # await asyncio.sleep(3600)
                await task.cancel()                
            except asyncio.exceptions.CancelledError:
                print("done")


    except RuntimeError as err:
        print('SIGINT or SIGTSTP raised')
        print("cleaning and exiting")
        sys.exit(1)    

def quit_window(icon, item):
    global loop,fastapi_thread

    print('shutdown icon')

    icon.stop()



    print('shutdown server')
    server.should_exit = True
    server.force_exit = True
    asyncio.run(server.shutdown())

    print(f'0:{asyncio.all_tasks(loop)}')
    try:
        if loop.is_running():
            # _logger.debug("Asked running asyncio loop to stop.")
            loop.call_soon_threadsafe(loop.stop)        
            tasks = asyncio.all_tasks(loop)
            print(tasks,'========')
            for task in tasks:
                try:
                    # await asyncio.sleep(3600)
                    task.cancel()           
                    with suppress(CancelledError):
                        loop.run_until_complete(task)
                except asyncio.exceptions.CancelledError:
                    print("done")


    except RuntimeError as err:
        print('SIGINT or SIGTSTP raised')
        print("cleaning and exiting")
        sys.exit(1)    
    print('shutdown root')

    root.destroy()

    asyncio.run(wait())

    print('close loop')



    print(f'1:{asyncio.all_tasks(loop)}')
    # loop.close()
    print('stop loop')

    loop.stop()
    # loop.run_until_complete(asyncio.gather(*[shutdown()]))
    # import os
    # os._exit(0)

def show_window(icon, item):
    icon.stop()
    root.after(0, root.deiconify)


def withdraw_window():
    root.withdraw()
    image = Image.open("assets/icon.ico")
    menu = (item("Quit", quit_window), item("Show", show_window))
    icon = pystray.Icon("name", image, "title", menu)
    # icon.run_detached()
    icon.run()

def start_fastapi_server(loop):
    import uvicorn
    global server
    config = uvicorn.Config(app, loop=loop, host="0.0.0.0", port=8000)
    server = uvicorn.Server(config)
    try:
        loop.run_until_complete(server.serve())
    except KeyboardInterrupt:
        print("Received Ctrl+C. Stopping gracefully...")
        # Cancel all running tasks
        for task in asyncio.Task.all_tasks():
            task.cancel()
        # Optionally: Close any open resources (sockets, files, etc.)
        # Cleanup code here
    finally:
        loop.close()




def start_tkinter_app(async_loop):
    global root, settings, db, canvas, locale
    root = tk.Tk()

    locale = 'en'
    start(locale, root, async_loop)

    root.protocol('WM_DELETE_WINDOW', withdraw_window)


    root.mainloop()




if __name__ == "__main__":
    global loop,fastapi_thread
    loop=None
    if sys.platform == 'win32':
        asyncio.get_event_loop().close()
        # On Windows, the default event loop is SelectorEventLoop, which does
        # not support subprocesses. ProactorEventLoop should be used instead.
        # Source: https://docs.python.org/3/library/asyncio-subprocess.html
        loop = asyncio.ProactorEventLoop()
        asyncio.set_event_loop(loop)
    else:
        loop = asyncio.get_event_loop()

    # Start FastAPI server in a separate thread
    fastapi_thread = threading.Thread(target=start_fastapi_server,args=(
            loop,)).start()


    start_tkinter_app(loop)
    loop.run_forever()
    loop.close()
```

**Comment by RobertCall** [comment] 2024-01-09 10:52
I have same effect then trying to close server from inside

## Example code
```
from fastapi import FastAPI
import uvicorn


class ServerRunner:
    def __init__(self):
        self.app = FastAPI()

        @self.app.get("/close")
        async def close():
            self.server.force_exit = True
            self.server.should_exit = True
            await self.server.shutdown()

        config = uvicorn.Config(self.app, host='0.0.0.0', port=5432, forwarded_allow_ips='*')
        self.server = uvicorn.Server(config)

    def run(self):
        self.server.run()


if __name__ == '__main__':
    runner = ServerRunner()
    runner.run()
```

## Output
```
INFO:     Started server process [3840]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5432 (Press CTRL+C to quit)
INFO:     127.0.0.1:58584 - "GET /close HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Finished server process [3840]
ERROR:    Traceback (most recent call last):
  File "D:\Projects\some_project\venv310\lib\site-packages\starlette\routing.py", line 686, in lifespan
    await receive()
  File "D:\Projects\some_project\venv310\lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError


Process finished with exit code 0
```

## Versions
```
(venv310) PS D:\Projects\some_project> python --version
Python 3.10.11
(venv310) PS D:\Projects\some_project> pip show uvicorn
Name: uvicorn
Version: 0.25.0
```

**Comment by kenn** [comment] 2024-01-23 08:15
This issue shows up repeatedly (like https://github.com/encode/uvicorn/issues/1160 ), and I hope it gets an attention.

Here's a workaround to silence this verbose error messages at exit.

Hope it helps!

```py
# Monkey patching to silence verbose error at uvicorn exit
# Put this code at the end of main.py

if is_dev_environment:
    get = asyncio.Queue.get

    async def new_get(self):
        try:
            return await get(self)
        except asyncio.exceptions.CancelledError:
            pass

    asyncio.Queue.get = new_get

```

**Comment by Kludex** [comment] 2024-04-13 12:46
I'll close this since I can't run the provided code. Please create a minimal, reproducible, example.

**Closed as not planned by Kludex** 2024-04-13 12:46 UTC
Labels: need confirmation

**Comment by JimiC** [comment] 2024-09-26 05:21
@Kludex Here's a code example to reproduce the issue.

```python

import asyncio

from uvicorn import Config, Server


async def test():
    server_config = Config(app="fastapi:FastAPI", factory=True)
    server = Server(config=server_config)
    await server.serve()


if __name__ == "__main__":
    asyncio.run(test())
```

**Comment by JimiC** [comment] 2024-09-26 07:31
@Kludex Well, the above code doesn't actually reproduces the issue.

After some more debugging I found that the exception is thrown in `LifespanOn.receive` and it has to do with the `receive_queue`.
Long story short, it all comes down to the fact that `lifespan.shutdown` doesn't get called in `server.shutdown` because `force_exit` is set to `True`. This is caused because `SIGINT` is added in `captured_signals` in `handle_exit` a second time. A simple guard clause there will solve the issue (most of the times).

Even handling the issue with the above proposed guard clause, the `asyncio.CancelledError` appears some times, so catching the `asyncio.CancelledError` in `LifespanOn.receive` should be highly considered. The way to handle it I leave it up to you.
