### ISSUE TITLE
gunicorn worker (uvicorn.workers.UvicornWorker) does not report request/s via statsd client

### ISSUE THREAD

**Issue by sileht** [Kludex/uvicorn#610] opened 2020-04-04 19:27 UTC
Hi,

gunicorn worker (uvicorn.workers.UvicornWorker) does not  report request/s via statsd client, like other gunicorn workers.

Regards,
Mehdi

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/610">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/610/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/610/pledge.svg">
</picture>
</a>

**Comment by Traktormaster** [comment] 2020-04-10 11:12
Hi!

I've just ran into this issue myself. After delving a bit into the codes of gunicorn and uvicorn, I can say the problem is simple, but not very trivial to fix.

The gunicorn statsd implementation is mixed with their logging facility. Which is a a little questionable, no wonder they have an [issue](https://github.com/benoitc/gunicorn/issues/1564) to refactor it. Since uvicorn has its own logging system and does not reuse the logger instance from gunicorn (even though it inherits it by forking), the statsd codes are never invoked.

I could not find an easy and nice way to make it work. The worker.log object would need to be accessible from the running http protocol, and even then the statsd logging could not be reused as-is since it's merged with the real logging. (it could lead to logging twice I think)

Anyways, depending on what you're using this can be circumvented in the framework level. I'm using Starlette and there is an [ASGI middleware](https://github.com/steinnes/timing-asgi) to send request metrics to statsd.

I know this is not a solution, but I wanted to write it down for future reference. Maybe someone will find it useful.

**Comment by sandys** [comment] 2021-03-17 09:10
im facing the same issue here. is there a workaround ? we are using fastapi

**Comment by damluji** [comment] 2021-08-25 14:26
Any updates please? ran into the same problem today.

**Comment by Kludex** [comment] 2024-04-13 12:26
Given that Gunicorn has the issue https://github.com/benoitc/gunicorn/issues/1564, and we are deprecating the workers within Uvicorn (https://github.com/encode/uvicorn/pull/2302).

- Feel free to recreate this issue on https://github.com/Kludex/uvicorn-worker

**Closed as completed by Kludex** 2024-04-13 12:26 UTC
Labels: user experience, workers/gunicorn
